build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

test_script:
  - "%PYTHON%/python.exe fulltext/data/winmake.py ci"

skip_commits:
  message: skip-ci
